// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ayludcnqyyznsyzhcytf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF5bHVkY25xeXl6bnN5emhjeXRmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0NTkxNzgsImV4cCI6MjA3MjAzNTE3OH0.uLBf8y4Gz6BtFhJOTr3MaEXyFJs1LGr3q1w-r7jK0bE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: false,
  },
  global: {
    headers: {
      'X-Client-Info': 'supabase-js-web'
    }
  }
});